import {
  mdiAccount,
  mdiAccountCircle,
  mdiButtonCursor,
  mdiCog,
  mdiDockLeft,
  mdiDotsVertical,
  mdiFormatFont,
  mdiFormTextbox,
  mdiFormSelect,
  mdiHome,
  mdiMenu,
  mdiPlayCircle,
  mdiTable,
  mdiViewDashboardOutline,
  mdiWindowMaximize,
  mdiSquareRoundedBadge,
  mdiViewGridOutline,
  mdiViewArrayOutline,
  mdiFormatLineSpacing,
  mdiRadioboxMarked,
  mdiTextBox,
} from '@mdi/js';

export const appIcons = [{ name: 'home', path: mdiHome },
      { name: 'account', path: mdiAccount },
      { name: 'cog', path: mdiCog },
      { name: 'menu', path: mdiMenu },
      { name: 'account-circle', path: mdiAccountCircle },
      { name: 'format-font', path: mdiFormatFont },
      { name: 'button-cursor', path: mdiButtonCursor },
      { name: 'dock-left', path: mdiDockLeft },
      { name: 'table', path: mdiTable },
      { name: 'view-dashboard-outline', path: mdiViewDashboardOutline },
      { name: 'view-grid-outline', path: mdiViewGridOutline },
      { name: 'view-array-outline', path: mdiViewArrayOutline },
      { name: 'spacing', path: mdiFormatLineSpacing },
      { name: 'dots-vertical', path: mdiDotsVertical },
      { name: 'window-maximize', path: mdiWindowMaximize },
      { name: 'form-textbox', path: mdiFormTextbox },
      { name: 'form-select', path: mdiFormSelect },
      { name: 'play', path: mdiPlayCircle },
      { name: 'snackbar', path: mdiSquareRoundedBadge},
      { name: 'radiobox-marked', path: mdiRadioboxMarked},
      { name: 'text-box', path: mdiTextBox},
      { name: 'grid', path: mdiViewGridOutline },
      { name: 'flex', path: mdiViewArrayOutline },
]